# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
